# Generated by Django 6.0.4 on 2026-04-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='parceiros/')),
                ('area_atuacao', models.CharField(max_length=100, verbose_name='Área de Atuação')),
                ('contato', models.CharField(help_text='Pode ser WhatsApp, Instagram ou Telefone', max_length=100)),
                ('link_site', models.URLField(blank=True, help_text='Link opcional para site ou rede social', null=True)),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
            },
        ),
    ]
