# Generated by Django 6.0.4 on 2026-04-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoEnciclopet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('categoria', models.CharField(choices=[('SAUDE', 'Saúde'), ('COMPORTAMENTO', 'Comportamento'), ('ALIMENTACAO', 'Alimentação'), ('CUIDADOS', 'Cuidados Gerais')], max_length=20)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='enciclopet/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
