# Generated by Django 6.0.4 on 2026-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artigoenciclopet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='animais/')),
                ('especie', models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato')], max_length=20)),
                ('idade', models.CharField(help_text='Ex: 2 anos, Filhote (3 meses)', max_length=50)),
                ('tamanho', models.CharField(blank=True, choices=[('PEQUENO', 'Pequeno'), ('MEDIO', 'Médio'), ('GRANDE', 'Grande')], help_text='Deixe em branco se for gato', max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('MACHO', 'Macho'), ('FEMEA', 'Fêmea')], max_length=20)),
                ('status', models.CharField(choices=[('ADOTAR', 'Para Adoção'), ('PERDIDO', 'Perdido'), ('ENCONTRADO', 'Encontrado')], default='ADOTAR', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
