# Generated by Django 6.0.4 on 2026-04-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtigoEnciclopet',
        ),
    ]
