# Generated by Django 6.0.4 on 2026-04-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_artigoenciclopet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='animais/galeria/')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionais', to='core.animal')),
            ],
        ),
    ]
