# Generated by Django 6.0.4 on 2026-04-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_animalfoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='animal',
            name='historia',
            field=models.TextField(blank=True, null=True, verbose_name='História'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tamanho',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
