# Generated by Django 6.0.4 on 2026-04-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_animal_data_cadastro_animal_historia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(help_text='Ex: 2 meses, 1 ano', max_length=50),
        ),
    ]
