# Generated by Django 6.0.4 on 2026-04-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_animal_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('Cachorro', 'Cachorro'), ('Gato', 'Gato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Fêmea', 'Fêmea')], max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('Disponível', 'Disponível'), ('Adotado', 'Adotado'), ('Em Tratamento', 'Em Tratamento'), ('Resgatado', 'Resgatado')], default='Disponível', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], help_text='Preencha apenas para cachorros', max_length=20, null=True),
        ),
    ]
