# Generated by Django 6.0.4 on 2026-04-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_animal_especie_alter_animal_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('ADOTAR', 'Para Adotar'), ('PERDIDO', 'Perdido'), ('ENCONTRADO', 'Encontrado')], default='ADOTAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=20, null=True),
        ),
    ]
