# Generated by Django 6.0.4 on 2026-04-21 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_animal_historia_alter_animal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 21, 22, 26, 23, 31242, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
