# Generated by Django 6.0.4 on 2026-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_animal_data_cadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(help_text='⚠️ Recomendado: Envie uma imagem com proporção 1x1 (quadrada) para o layout ficar bonito.', upload_to='animais/'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(choices=[('Filhote', 'Filhote'), ('Adulto', 'Adulto'), ('Idoso', 'Idoso')], default='Adulto', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], help_text='⚠️ Preencha APENAS para cachorros. Deixe em branco se for gato.', max_length=20, null=True),
        ),
    ]
